spring:
    application:
        name: account-contract
    cloud:
        consul:
            discovery:
                instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}"
                instance-zone: zone1